version: '3.1'

services:
  server:
    container_name: node-server
    build: 
      context: .
    restart: always
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}
    depends_on:
      - db

  db:
    container_name: db-postgres
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: '${DB_NAME}'
      POSTGRES_USER: '${DB_USER}'
      POSTGRES_PASSWORD: '${DB_PASS}'
    ports:
      - 5000:5432  